# Staging Configuration for Project Athena
# Production-like environment for testing and validation

# Text modality configuration
text:
  enabled: true
  model_name: "meta-llama/Llama-2-13b-chat-hf"  # Mid-size model for staging
  threshold: 0.8
  batch_size: 16
  max_input_size: 2048
  preprocessing:
    normalize_unicode: true
    remove_control_chars: true
    preserve_formatting: false
    max_length: 8000
  postprocessing:
    include_explanations: false
    include_confidence_scores: true

# Image modality configuration
image:
  enabled: true
  model_name: "meta-cv/clip-vit-large-patch14"
  threshold: 0.85
  batch_size: 8
  max_input_size: 224
  preprocessing:
    target_size: [224, 224]
    normalize: true
    convert_mode: "RGB"
    quality_threshold: 0.7
  postprocessing:
    include_bounding_boxes: false
    include_heatmaps: true

# Audio modality configuration
audio:
  enabled: true
  model_name: "meta-audio/wav2vec2-large-960h"
  threshold: 0.8
  batch_size: 4
  max_input_size: 16000
  preprocessing:
    target_sr: 16000
    normalize_volume: true
    remove_silence: true
    max_duration: 180
  postprocessing:
    include_timestamps: false
    include_transcription: true

# Video modality configuration
video:
  enabled: true
  model_name: "meta-video/videomae-large"
  threshold: 0.85
  batch_size: 2
  max_input_size: 16
  preprocessing:
    target_fps: 1.0
    max_frames: 20
    extract_audio: true
    quality_filter: true
  postprocessing:
    include_frame_analysis: false
    include_temporal_features: true

# Meta AI integration settings
meta_integration:
  llama_models: ["llama-7b", "llama-13b", "llama-70b"]
  api_endpoint: "https://api-staging.meta.ai/v1"
  api_key: null  # Will be loaded from environment
  rate_limit: 500
  timeout: 45
  retry_attempts: 3
  use_pytorch_integration: true
  enable_fair_research_mode: true

# Ethics thresholds (production-like but slightly relaxed)
ethics_thresholds:
  harmful_content: 0.88
  bias_detection: 0.78
  privacy_violation: 0.93
  misinformation: 0.83
  toxicity: 0.78
  hate_speech: 0.88
  violence: 0.93
  sexual_content: 0.88
  child_safety: 0.98
  copyright_infringement: 0.83

# RLHF configuration
rlhf:
  enabled: true
  model_path: "models/rlhf/staging-model"
  learning_rate: 5e-6
  batch_size: 8
  num_epochs: 2
  max_length: 512
  temperature: 0.8
  top_p: 0.9
  use_wandb: true
  checkpoint_interval: 100

# Constitutional AI configuration
constitutional_ai:
  enabled: true
  constitution_path: "configs/constitution_staging.yaml"
  principles: ["helpfulness", "harmlessness", "honesty", "transparency", "fairness"]
  reasoning_model: "meta-llama/Llama-2-13b-chat-hf"
  max_reasoning_steps: 4
  confidence_threshold: 0.8

# General settings
logging_level: "INFO"
cache_enabled: true
cache_ttl: 3600  # 1 hour
monitoring_enabled: true
metrics_port: 8080
api_port: 8000

# Staging-specific settings
staging_settings:
  performance_testing: true
  load_testing_enabled: true
  security_testing: true
  data_validation_strict: true
  audit_all_requests: true
  synthetic_data_testing: true
  
# Database settings
database:
  host: "staging-db.athena.internal"
  port: 5432
  name: "athena_staging"
  ssl_mode: "require"
  connection_pool_size: 20
  
# Redis settings
redis:
  host: "staging-redis.athena.internal"
  port: 6379
  db: 0
  ssl: true
  connection_pool_size: 10

# Security settings
security:
  encryption_enabled: true
  audit_logging: true
  access_control_enabled: true
  rate_limiting_enabled: true
  session_timeout: 3600